# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          館
paginate:       5
baseurl:        ""
url:            "https://blog.lixd.club"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         xiaodong.li
  url:          http://blog.lixd.club
  email:        lixd@outlook.it

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/li-xd/li-xd.github.io

# Gems
gems:
  - jekyll-paginate
